[package]
name = "gameboy"
version = "0.1.0"
authors = ["Tomoki Imai <tomo832@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.113.0"
image = "0.23.9"